trigger:
- main  # Adjust this to your branch name

pool:
  vmImage: 'windows-latest'  # Use the appropriate image for your environment

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'  # Specify your .NET version
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    # Install Playwright browsers
    npm install -g @playwright/test
    npx playwright install --with-deps
  displayName: 'Install Playwright and Browsers'

- powershell: |
    if (!(Test-Path -Path "$Env:USERPROFILE\AppData\Local\ms-playwright")) {
        ./bin/Debug/net6.0/playwright.ps1 install
    }
  displayName: 'Install Playwright browsers using PowerShell script'

- script: |
    dotnet restore
    dotnet build
  displayName: 'Restore and Build'

- script: |
    dotnet test --logger:trx --filter "Category=RunInCI"
  displayName: 'Run Tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/*.xml'
    failOnError: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/screenshots'
    ArtifactName: 'Screenshots'
    publishLocation: 'Container'
