trigger:
- main  # Adjust this to your branch name

pool:
  vmImage: 'windows-latest'  # Use the appropriate image for your environment

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'  # Specify your .NET version
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    dotnet restore
    dotnet build
  displayName: 'Restore and Build'

# Install Playwright and its required browsers for .NET
- script: |
    # Force Playwright to install its browser dependencies
    dotnet tool install -g Microsoft.Playwright.CLI
    playwright install chromium firefox webkit
  displayName: 'Install Playwright and Browsers'

- script: |
    dotnet test --logger:"trx;LogFileName=test-results.trx" --filter "Category=RunInCI"
  displayName: 'Run Tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/*.trx'
    failOnError: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/TestResults'
    ArtifactName: 'TestResults'
    publishLocation: 'Container'
