trigger:
- main  # Adjust this to your branch name

pool:
  vmImage: 'windows-latest'  # Use the appropriate image for your environment

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'  # Specify your .NET version
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    # Install Playwright browsers
    npx playwright install --with-deps
  displayName: 'Install Playwright Browsers'

- script: |
    dotnet restore
    dotnet build
  displayName: 'Restore and Build'

- script: |
    dotnet test --logger:trx --filter FullyQualifiedName~SITS_Test_Automation.Tests.UITest.Tests.SmokeTest.TestSSOLogin
  displayName: 'Run Tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/*.xml'
    failOnError: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'path/to/screenshots'  # Adjust this path to where your screenshots are saved
    ArtifactName: 'Screenshots'
    publishLocation: 'Container'
